---
title: "Class List"
---

This page lists the class meetings and the corresponding materials.

The slide decks are designed for class structure and discussion. The book chapters give the slower narrative version, and the notebooks are where students experiment with the ideas computationally.

| Week | Class Topic | Slides | Notebook | Book |
|---:|---|---|---|---|
| 1 | Images as mathematical objects | [slides](week-01-image-formation.html) | [notebook](../notebooks/week01_image_formation.ipynb) / [Colab](https://colab.research.google.com/github/lnajman/math435-mathematical-imaging/blob/main/notebooks/week01_image_formation.ipynb) | [chapter](../book/week-01-image-formation.html) |
| 2 | Convolution and blur | [slides](week-02-convolution-blur.html) | [notebook](../notebooks/week02_convolution_blur.ipynb) / [Colab](https://colab.research.google.com/github/lnajman/math435-mathematical-imaging/blob/main/notebooks/week02_convolution_blur.ipynb) | [chapter](../book/week-02-convolution-blur.html) |
| 3 | Fourier transform in imaging | [slides](week-03-fourier-imaging.html) | [notebook](../notebooks/week03_fourier_imaging.ipynb) / [Colab](https://colab.research.google.com/github/lnajman/math435-mathematical-imaging/blob/main/notebooks/week03_fourier_imaging.ipynb) | [chapter](../book/week-03-fourier-imaging.html) |
| 4 | Noise models and likelihoods | [slides](week-04-noise-likelihood.html) | [notebook](../notebooks/week04_noise_likelihood.ipynb) / [Colab](https://colab.research.google.com/github/lnajman/math435-mathematical-imaging/blob/main/notebooks/week04_noise_likelihood.ipynb) | [chapter](../book/week-04-noise-likelihood.html) |
| 5 | Ill-posed inverse problems | [slides](week-05-ill-posed-inverse-problems.html) | [notebook](../notebooks/week05_ill_posed_inverse_problems.ipynb) / [Colab](https://colab.research.google.com/github/lnajman/math435-mathematical-imaging/blob/main/notebooks/week05_ill_posed_inverse_problems.ipynb) | [chapter](../book/week-05-ill-posed-inverse-problems.html) |
| 6 | Tikhonov regularization | [slides](week-06-tikhonov-regularization.html) | [notebook](../notebooks/week06_tikhonov_regularization.ipynb) / [Colab](https://colab.research.google.com/github/lnajman/math435-mathematical-imaging/blob/main/notebooks/week06_tikhonov_regularization.ipynb) | [chapter](../book/week-06-tikhonov-regularization.html) |
| 7 | Variational formulation | [slides](week-07-variational-formulation.html) | [notebook](../notebooks/week07_variational_formulation.ipynb) / [Colab](https://colab.research.google.com/github/lnajman/math435-mathematical-imaging/blob/main/notebooks/week07_variational_formulation.ipynb) | [chapter](../book/week-07-variational-formulation.html) |
| 8 | Total Variation regularization | [slides](week-08-total-variation.html) | [notebook](../notebooks/week08_total_variation.ipynb) / [Colab](https://colab.research.google.com/github/lnajman/math435-mathematical-imaging/blob/main/notebooks/week08_total_variation.ipynb) | [chapter](../book/week-08-total-variation.html) |
| 9 | Optimization methods | [slides](week-09-optimization-methods.html) | [notebook](../notebooks/week09_optimization_methods.ipynb) / [Colab](https://colab.research.google.com/github/lnajman/math435-mathematical-imaging/blob/main/notebooks/week09_optimization_methods.ipynb) | [chapter](../book/week-09-optimization-methods.html) |
| 10 | Sparse reconstruction | [slides](week-10-sparse-reconstruction.html) | [notebook](../notebooks/week10_sparse_reconstruction.ipynb) / [Colab](https://colab.research.google.com/github/lnajman/math435-mathematical-imaging/blob/main/notebooks/week10_sparse_reconstruction.ipynb) | [chapter](../book/week-10-sparse-reconstruction.html) |
| 11 | Wavelets and multiscale representation | [slides](week-11-wavelets.html) | [notebook](../notebooks/week11_wavelets.ipynb) / [Colab](https://colab.research.google.com/github/lnajman/math435-mathematical-imaging/blob/main/notebooks/week11_wavelets.ipynb) | [chapter](../book/week-11-wavelets.html) |
| 12 | Model-based vs data-driven imaging | [slides](week-12-model-data.html) | [notebook](../notebooks/week12_model_data.ipynb) / [Colab](https://colab.research.google.com/github/lnajman/math435-mathematical-imaging/blob/main/notebooks/week12_model_data.ipynb) | [chapter](../book/week-12-model-data.html) |
| 13 | Plug-and-play and learned regularization | [slides](week-13-plug-and-play.html) | [notebook](../notebooks/week13_plug_and_play.ipynb) / [Colab](https://colab.research.google.com/github/lnajman/math435-mathematical-imaging/blob/main/notebooks/week13_plug_and_play.ipynb) | [chapter](../book/week-13-plug-and-play.html) |
| 14 | Stability, robustness, and ethics | [slides](week-14-stability-robustness-ethics.html) | [notebook](../notebooks/week14_stability_robustness.ipynb) / [Colab](https://colab.research.google.com/github/lnajman/math435-mathematical-imaging/blob/main/notebooks/week14_stability_robustness.ipynb) | [chapter](../book/week-14-stability-robustness-ethics.html) |
| 15 | Project presentations and oral defenses | [project page](../project/index.html) | - | - |
