#!/usr/bin/env python3
"""Convert a supplied official Word syllabus into the Quarto syllabus page."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "syllabus.qmd"
QUARTO = ROOT / "scripts" / "quarto"

SECTION_HEADINGS = {
    "Prerequisites", "Corequisites", "Course Catalog Description", "Textbook",
    "Reference Materials", "Course Structure & Learning Methodology", "Course Topics",
    "Laboratory and/or Computing/Digital Resources", "Assessment", "Grading Scheme",
    "Academic Integrity Statement", "Copyright and Plagiarism", "Syllabus supplement",
    "Instructor Policy on Late Submission of Assignments", "Practice and feedback",
    "Student support", "Reading guidance and schedule", "Weekly plan (Tentative)",
    "Additional information", "Revision record",
}
POLICY_HEADINGS = {"Assessment", "Project", "Calculator Policy", "Classroom Policies"}


def plain_text(value: object) -> str:
    if isinstance(value, list):
        return "".join(plain_text(item) for item in value)
    if not isinstance(value, dict):
        return ""
    kind = value.get("t")
    content = value.get("c", [])
    if kind == "Str":
        return content
    if kind in {"Math", "Code"}:
        return content[1]
    if kind in {"Space", "SoftBreak", "LineBreak"}:
        return " "
    if kind in {"Link", "Image", "Span"}:
        return plain_text(content[1])
    return plain_text(content)


def heading(text: str, level: int = 2) -> dict:
    return {"t": "Header", "c": [level, ["", [], []], [{"t": "Str", "c": text}]]}


def table_rows(table: dict) -> list:
    # Pandoc tables store rows separately in the head, bodies, and foot.
    _, _, _, head, bodies, foot = table["c"]
    return head[1] + [row for body in bodies for row in body[2] + body[3]] + foot[1]


def format_blocks(blocks: list, *, inside_policy: bool = False) -> list:
    formatted = []
    section = ""
    for block in blocks:
        kind = block["t"]
        if kind == "Table":
            rows = table_rows(block)
            if len(block["c"][2]) == 1:
                policy = [item for row in rows for cell in row[1] for item in cell[4]]
                formatted.extend(format_blocks(policy, inside_policy=True))
                continue
            if section.casefold() == "weekly plan (tentative)":
                for row in rows:
                    cells = row[1]
                    week = plain_text(cells[0][4]).strip()
                    if len(cells) == 2 and week.isdigit():
                        formatted.append(heading(f"Week {int(week)}", level=3))
                        formatted.extend(cells[1][4])
                    elif week.casefold() != "week #":
                        raise ValueError("Unexpected weekly-plan row; review the Word table.")
                continue
        if kind in {"Para", "Plain"}:
            text = plain_text(block["c"]).strip()
            if not text:
                continue
            if inside_policy and text in POLICY_HEADINGS:
                formatted.append(heading(text, level=3))
                continue
            if text.casefold() in {name.casefold() for name in SECTION_HEADINGS}:
                section = text
                formatted.append(heading(text))
                continue
            if text.startswith("Course Learning Outcomes ("):
                formatted.append(heading(text))
                continue
        formatted.append(block)
    return formatted


def syllabus_markdown(docx_path: Path) -> str:
    result = subprocess.run(
        [str(QUARTO), "pandoc", str(docx_path), "--to=json", "--track-changes=accept"],
        cwd=ROOT, check=True, capture_output=True, text=True,
    )
    document = json.loads(result.stdout)
    document["blocks"] = [heading("Course Information")] + format_blocks(document["blocks"])
    result = subprocess.run(
        [str(QUARTO), "pandoc", "--from=json", "--to=gfm", "--wrap=none"],
        input=json.dumps(document), cwd=ROOT, check=True, capture_output=True, text=True,
    )
    return result.stdout.replace("  \n", "<br>\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("docx", type=Path, help="Path to the current official Word syllabus.")
    args = parser.parse_args()
    docx_path = args.docx.expanduser()
    if not docx_path.is_file():
        raise SystemExit(f"Could not find syllabus Word document: {docx_path}")

    body = syllabus_markdown(docx_path)
    page = (
        '---\ntitle: "Syllabus"\ntoc: true\ntoc-depth: 3\n---\n\n'
        '<!-- Generated by scripts/convert_syllabus_docx.py; update the source Word document '
        'and regenerate this page instead of editing its policies by hand. -->\n'
        f'<!-- Source: {docx_path.name} -->\n\n'
        f'{body}'
    )
    OUTPUT.write_text(page, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} from {docx_path}")


if __name__ == "__main__":
    main()
